-- ClavelParts · migracion para ficha de producto y multiples fotos
-- Ejecutar en Supabase SQL Editor sobre una base ya existente.

alter table public.productos
  add column if not exists vendedor_id bigint,
  add column if not exists descripcion_corta text,
  add column if not exists descripcion_larga text,
  add column if not exists familia text default null,
  add column if not exists material text,
  add column if not exists garantia_meses integer,
  add column if not exists peso_kg numeric(10, 3),
  add column if not exists alto_cm numeric(10, 2),
  add column if not exists ancho_cm numeric(10, 2),
  add column if not exists largo_cm numeric(10, 2);

create table if not exists public.fotos_producto (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  url text not null,
  orden integer not null default 1,
  created_at timestamptz not null default now(),
  unique (producto_id, orden)
);

create index if not exists idx_productos_familia on public.productos(familia) where familia is not null;
create index if not exists idx_productos_activo on public.productos(activo);
create index if not exists idx_productos_vendedor_id on public.productos(vendedor_id);
create index if not exists idx_productos_numero_parte_oem on public.productos(numero_parte_oem);
create index if not exists idx_productos_especificaciones on public.productos using gin(especificaciones);
create index if not exists idx_compatibilidades_producto on public.compatibilidades(producto_id);
create index if not exists idx_fotos_producto_producto_orden on public.fotos_producto(producto_id, orden);

create or replace view public.vista_catalogo as
select
  p.id as product_id,
  ma.nombre as marca,
  mo.nombre as modelo,
  ve.anio,
  ve.version,
  ve.motor_codigo,
  coalesce(gr.nombre, 'Otros') as grupo,
  coalesce(sg.nombre, 'General') as subgrupo,
  p.tipo_pieza,
  p.sku,
  p.producto,
  p.descripcion_corta,
  p.descripcion_larga,
  p.marca_pieza,
  p.numero_parte_oem,
  p.precio,
  p.precio_oferta,
  p.stock,
  p.liquidacion,
  p.activo,
  p.material,
  p.garantia_meses,
  p.peso_kg,
  p.alto_cm,
  p.ancho_cm,
  p.largo_cm,
  p.especificaciones,
  p.vendedor,
  p.imagen_url,
  p.familia
from public.compatibilidades c
join public.productos p on p.id = c.producto_id
join public.versiones ve on ve.id = c.version_id
join public.modelos mo on mo.id = ve.modelo_id
join public.marcas ma on ma.id = mo.marca_id
left join public.grupos gr on gr.id = p.grupo_id
left join public.subgrupos sg on sg.id = p.subgrupo_id;

create or replace view public.vista_tre_catalogo as
select
  p.id     as product_id,
  ma.id    as marca_id,
  ma.nombre as marca,
  mo.id    as modelo_id,
  mo.nombre as modelo,
  ve.anio,
  ve.version,
  ve.motor_codigo,
  coalesce(gr.nombre, 'Otros')   as grupo,
  coalesce(sg.nombre, 'General') as subgrupo,
  p.tipo_pieza,
  p.sku,
  p.producto,
  p.descripcion_corta,
  p.descripcion_larga,
  p.marca_pieza,
  p.numero_parte_oem,
  p.precio,
  p.precio_oferta,
  p.stock,
  p.liquidacion,
  p.activo,
  p.material,
  p.garantia_meses,
  p.peso_kg,
  p.alto_cm,
  p.ancho_cm,
  p.largo_cm,
  p.especificaciones,
  p.vendedor,
  p.imagen_url,
  p.familia
from public.compatibilidades c
join public.productos p on p.id = c.producto_id
join public.versiones ve on ve.id = c.version_id
join public.modelos mo on mo.id = ve.modelo_id
join public.marcas ma on ma.id = mo.marca_id
left join public.grupos gr on gr.id = p.grupo_id
left join public.subgrupos sg on sg.id = p.subgrupo_id
where p.familia = 'tre_performance'
  and p.activo = true;