-- ClavelParts · esquema base para Supabase
-- Ejecutar en Supabase SQL Editor

create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.modelos (
  id bigint generated by default as identity primary key,
  marca_id bigint not null references public.marcas(id) on delete cascade,
  nombre text not null,
  unique (marca_id, nombre)
);

create table if not exists public.versiones (
  id bigint generated by default as identity primary key,
  modelo_id bigint not null references public.modelos(id) on delete cascade,
  anio integer not null,
  version text not null,
  motor_codigo text not null,
  unique (modelo_id, anio, version, motor_codigo)
);

create table if not exists public.grupos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  orden integer not null default 100
);

create table if not exists public.subgrupos (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.grupos(id) on delete cascade,
  nombre text not null,
  orden integer not null default 100,
  unique (grupo_id, nombre)
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  grupo_id bigint references public.grupos(id) on delete set null,
  subgrupo_id bigint references public.subgrupos(id) on delete set null,
  vendedor_id bigint,
  tipo_pieza text not null,
  sku text not null unique,
  producto text not null,
  descripcion_corta text,
  descripcion_larga text,
  marca_pieza text,
  numero_parte_oem text,
  precio numeric(12, 2),
  precio_oferta numeric(12, 2),
  stock integer not null default 0,
  liquidacion boolean not null default false,
  activo boolean not null default true,
  familia text,
  material text,
  garantia_meses integer,
  peso_kg numeric(10, 3),
  alto_cm numeric(10, 2),
  ancho_cm numeric(10, 2),
  largo_cm numeric(10, 2),
  especificaciones jsonb,
  vendedor text,
  imagen_url text
);

create table if not exists public.fotos_producto (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  url text not null,
  orden integer not null default 1,
  created_at timestamptz not null default now(),
  unique (producto_id, orden)
);

create table if not exists public.vendedores (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  nombre text,
  nombre_comercial text,
  razon_social text,
  email text
);

create table if not exists public.compatibilidades (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  version_id bigint not null references public.versiones(id) on delete cascade,
  unique (producto_id, version_id)
);

create index if not exists idx_modelos_marca_id on public.modelos(marca_id);
create index if not exists idx_versiones_modelo_anio on public.versiones(modelo_id, anio);
create index if not exists idx_productos_grupo_subgrupo on public.productos(grupo_id, subgrupo_id);
create index if not exists idx_productos_sku on public.productos(sku);
create index if not exists idx_productos_familia on public.productos(familia) where familia is not null;
create index if not exists idx_productos_activo on public.productos(activo);
create index if not exists idx_productos_vendedor_id on public.productos(vendedor_id);
create index if not exists idx_productos_numero_parte_oem on public.productos(numero_parte_oem);
create index if not exists idx_productos_especificaciones on public.productos using gin(especificaciones);
create index if not exists idx_compatibilidades_version on public.compatibilidades(version_id);
create index if not exists idx_compatibilidades_producto on public.compatibilidades(producto_id);
create index if not exists idx_fotos_producto_producto_orden on public.fotos_producto(producto_id, orden);

create or replace view public.vista_catalogo as
select
  p.id as product_id,
  ma.nombre as marca,
  mo.nombre as modelo,
  ve.anio,
  ve.version,
  ve.motor_codigo,
  coalesce(gr.nombre, 'Otros') as grupo,
  coalesce(sg.nombre, 'General') as subgrupo,
  p.tipo_pieza,
  p.sku,
  p.producto,
  p.descripcion_corta,
  p.descripcion_larga,
  p.marca_pieza,
  p.numero_parte_oem,
  p.precio,
  p.precio_oferta,
  p.stock,
  p.liquidacion,
  p.activo,
  p.material,
  p.garantia_meses,
  p.peso_kg,
  p.alto_cm,
  p.ancho_cm,
  p.largo_cm,
  p.especificaciones,
  p.vendedor,
  p.imagen_url,
  p.familia
from public.compatibilidades c
join public.productos p on p.id = c.producto_id
join public.versiones ve on ve.id = c.version_id
join public.modelos mo on mo.id = ve.modelo_id
join public.marcas ma on ma.id = mo.marca_id
left join public.grupos gr on gr.id = p.grupo_id
left join public.subgrupos sg on sg.id = p.subgrupo_id;
